version: '3.9'

services:
  eth_spike_real_time:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    volumes:
      - ./app:/home/jovyan/app
    #command: tail -F anything
    environment:
      - ACCOUNT_SID
      - AUTH_TOKEN
      - TWILIO_PHONE_NUMBER